### ISSUE TITLE
Documentation for 2.0

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#264]
This is an umbrella issue to cover all the things we need regarding documentation for 2.0:

* [x] Examples: #125
* [x] Enable javadoc failures when running `mvn verify` (mvn javadoc plugin) #275
* [x] Check missing javadoc, missing javadoc tags and internal and external links are working properly
    * [x] api #267 
    * [x] core https://github.com/cloudevents/sdk-java/pull/313
    * [x] formats/json-jackson https://github.com/cloudevents/sdk-java/pull/319
    * [x] http/basic #320
    * [x] http/restful-ws #320
    * [x] http/vertx #320
    * [x] kafka #321
    * [x] amqp #322
    * [x] spring #323
* [ ] Update website:
  * [x] Check website technical details (jekyll version, theme version, ...)
  * [x] Develop a page that shows the basic features to operate with CloudEvents: CloudEvent, CloudEventBuilder, how to interact with `CloudEventData` and map it to pojos, ... #324
  * [x] Develop a page that shows the basics of using `EventFormat`, showing an example for json (using jackson) #324
  * [x] Move readmes of separate modules to website pages, one page per module (and point modules back to website pages) #324
    * [x] core and api (they might require a single page for both) #324
    * [x] formats/json-jackson #324
    * [x] http/basic #324
    * [x] http/restful-ws #324
    * [x] http/vertx #324
    * [x] kafka #324
  * [ ] Develop a page that explains some advanced stuff, like how to create your own `CloudEvent`, how to create a protocol binding, how to create your own event format, etc

If you're going to work in one of the issues described above, please write it down in the comments.

**Comment by slinkydeveloper** [comment]
I'm gonna start working on the technical details of the website

**Comment by slinkydeveloper** [comment]
Checked javadocs for api module: https://github.com/cloudevents/sdk-java/pull/267

**Comment by slinkydeveloper** [comment]
Run javadoc builds with mvn verify https://github.com/cloudevents/sdk-java/pull/275

**Comment by slinkydeveloper** [comment]
Working on core module docs

**Comment by slinkydeveloper** [comment]
Working on jackson

**Comment by slinkydeveloper** [comment]
Working on all the http/* modules javadocs

**Comment by slinkydeveloper** [comment]
Working on kafka javadocs

**Comment by slinkydeveloper** [comment]
Working on amqp javadocs

**Comment by slinkydeveloper** [comment]
Working on spring javadocs

**Comment by slinkydeveloper** [comment]
Working on some basic pages for the website
